import { setupShared, request, connectSession } from "./shared.js";
const $ = id => document.getElementById(id); let ws, scanner;
setupShared({ chatLog: $("chatLog"), statusStrip: $("statusStrip"), reconnecting: $("reconnecting"), role: "OFFICIAL" });
const codeFromUrl = new URLSearchParams(location.search).get("session"); if (codeFromUrl) $("sessionInput").value = codeFromUrl.toUpperCase();
$("joinButton").onclick = join; $("sessionInput").addEventListener("keydown", e => { if (e.key === "Enter") join(); }); $("sendText").onclick = () => sendText($("textInput").value); $("micButton").onclick = startMic; $("leaveButton").onclick = () => { ws?.close(); location.href = "./official.html"; };
if (window.Html5QrcodeScanner) { scanner = new Html5QrcodeScanner("qr-reader", { fps: 8, qrbox: 220 }, false); scanner.render(text => { const match = text.match(/[?&]session=([A-Za-z0-9]{6})/) || text.match(/\b([A-Za-z0-9]{6})\b/); if (match) { $("sessionInput").value = match[1].toUpperCase(); scanner.clear(); join(); } }, () => {}); }
async function join() { const id = $("sessionInput").value.trim().toUpperCase(); if (!/^[A-Z0-9]{6}$/.test(id)) return error("Enter the six-character session code."); try { await request(`/api/sessions/${id}/status`); $("joinScreen").classList.add("hidden"); $("officialView").classList.remove("hidden"); $("officialView").classList.add("flex"); ws = await connectSession(id, "OFFICIAL"); } catch (e) { error(e.message); } }
function sendText(text) { const value = text.trim(); if (!value) return; ws?.sendTranscript(value); $("textInput").value = ""; $("micState").textContent = "Sending…"; setTimeout(() => $("micState").textContent = "Tap to speak", 700); }
function startMic() { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) return error("Speech recognition is not supported by this browser."); const recognition = new Recognition(); recognition.lang = "en-IN"; recognition.interimResults = false; recognition.onstart = () => { $("micButton").className = "h-20 w-20 animate-pulse rounded-full bg-blue-600 text-lg text-white shadow-lg"; $("micButton").textContent = "…"; $("micState").textContent = "Listening…"; }; recognition.onresult = e => sendText(e.results[0][0].transcript); recognition.onerror = () => error("Could not hear that. Please try again or type your reply."); recognition.onend = () => { $("micButton").className = "h-20 w-20 rounded-full bg-gray-900 text-lg text-white shadow-lg transition hover:bg-black"; $("micButton").textContent = "🎙"; if ($("micState").textContent === "Listening…") $("micState").textContent = "Tap to speak"; }; recognition.start(); }
function error(message) { $("joinError").textContent = message; $("joinError").hidden = false; }
