const backend = `${location.protocol === "https:" ? "https" : "http"}://${location.hostname}:8080`;
let chat, status, reconnectBanner, activeRole, activeSession, client, rendered = new Set();
export function setupShared({ chatLog, statusStrip, reconnecting, role }) { chat = chatLog; status = statusStrip; reconnectBanner = reconnecting; activeRole = role; }
export async function request(path, options) { const response = await fetch(`${backend}${path}`, options); if (!response.ok) throw new Error(response.status === 404 ? "That session code was not found." : "Could not contact the ISL Bridge server."); return response.json(); }
export async function loadHistory(sessionId) { const data = await request(`/api/sessions/${sessionId}/history`); data.messages.forEach(renderMessage); }
export function renderMessage(payload) { if (!payload?.englishText) return; const key = `${payload.originRole}|${payload.englishText}|${payload.hindiText || ""}`; if (rendered.has(key)) return; rendered.add(key); const nearBottom = chat.scrollHeight - chat.scrollTop - chat.clientHeight < 80; const signer = payload.originRole === "SIGNER"; const card = document.createElement("article"); card.className = `rounded-2xl border p-4 ${signer ? "border-blue-200 bg-blue-50/80" : "border-gray-200 bg-gray-50"}`; card.innerHTML = `<p class="mb-1 text-xs font-bold uppercase tracking-wide ${signer ? "text-blue-700" : "text-gray-600"}">${signer ? "Signer" : "Official"}</p><p class="font-medium text-gray-900"></p>${payload.hindiText ? '<p class="mt-2 text-sm text-gray-600"></p>' : ""}`; card.querySelector("p:nth-child(2)").textContent = payload.englishText; if (payload.hindiText) card.querySelector("p:nth-child(3)").textContent = payload.hindiText; chat.append(card); if (nearBottom) chat.scrollTop = chat.scrollHeight; }
export function renderStatus(payload) { const otherConnected = activeRole === "SIGNER" ? payload.officialConnected : payload.signerConnected; const other = activeRole === "SIGNER" ? "Official" : "Signer"; status.textContent = `Session: ${activeSession} · ${otherConnected ? "● " + other + " connected" : other + " disconnected / waiting"}`; status.className = `mb-4 rounded-xl border px-4 py-3 text-sm font-medium ${otherConnected ? "border-blue-100 bg-white text-gray-600" : "border-amber-200 bg-amber-50 text-amber-800"}`; window.dispatchEvent(new CustomEvent("isl-status", { detail: payload })); }
export async function connectSession(sessionId, role) { activeSession = sessionId.toUpperCase(); activeRole = role; await loadHistory(activeSession); client = new StompJs.Client({ webSocketFactory: () => new SockJS(`${backend}/ws`), reconnectDelay: 1000, reconnectTimeMode: "exponential", maxReconnectDelay: 8000 }); client.onConnect = () => { reconnectBanner?.classList.add("hidden"); client.subscribe(`/topic/session/${activeSession}`, message => { const envelope = JSON.parse(message.body); if (envelope.type === "TRANSLATED_MESSAGE") renderMessage(envelope.payload); if (envelope.type === "SESSION_STATUS") renderStatus(envelope.payload); }); client.publish({ destination: `/app/session/${activeSession}/join`, body: envelope("SESSION_STATUS", role, {}) }); loadHistory(activeSession).catch(console.warn); }; client.onWebSocketClose = () => reconnectBanner?.classList.remove("hidden"); client.onStompError = frame => console.warn("STOMP error", frame.headers.message); client.activate(); return { sendKeyword: (keyword, confidence) => send("keyword", "KEYWORD_INPUT", { keyword, confidence }), sendTranscript: text => send("transcript", "SPEECH_TRANSCRIPT", { text }), close: () => client?.deactivate() }; }
function envelope(type, sender, payload) { return JSON.stringify({ type, sessionId: activeSession, sender, payload, timestamp: new Date().toISOString() }); }
function send(route, type, payload) { if (client?.connected) client.publish({ destination: `/app/session/${activeSession}/${route}`, body: envelope(type, activeRole, payload) }); }
export { backend };
