import { setupShared, request, connectSession, backend } from "./shared.js";
import { startCamera, describeCameraError } from "./camera.js";
import { createHandLandmarker, drawHandOverlay, interpretHandLandmarkerResult, isHandLandmarksResult } from "./landmarker.js";
import { createInference } from "./inference.js";
const $ = id => document.getElementById(id); let ws, landmarker, context, inference, lastSent = 0, stream;
setupShared({ chatLog: $("chatLog"), statusStrip: $("statusStrip"), reconnecting: $("reconnecting"), role: "SIGNER" });
$("startSession").onclick = createSession;
window.addEventListener("isl-status", event => { if (event.detail.officialConnected && $("translate").classList.contains("hidden")) showTranslator(); });
window.addEventListener("beforeunload", () => { ws?.close(); stream?.getTracks().forEach(track => track.stop()); });
async function createSession() { try { const { sessionId } = await request("/api/sessions", { method: "POST" }); $("landing").classList.add("hidden"); $("invite").classList.remove("hidden"); $("sessionCode").textContent = sessionId; new QRCode($("qrcode"), { text: `${location.origin}${location.pathname.replace(/index\.html$/, "")}official.html?session=${sessionId}`, width: 176, height: 176 }); ws = await connectSession(sessionId, "SIGNER"); $("inviteConnection").textContent = `Connected to session ${sessionId}.`; } catch (error) { $("landingError").textContent = error.message; $("landingError").hidden = false; } }
async function showTranslator() { $("invite").classList.add("hidden"); $("translate").classList.remove("hidden"); try { stream = await startCamera($("video")); $("cameraOverlay").remove(); const result = await createHandLandmarker(); landmarker = result.instance; context = $("overlay").getContext("2d"); inference = await createInference({ onPrediction: prediction => { $("prediction").textContent = `${prediction.label.replaceAll("_", " ")} (${(prediction.confidence * 100).toFixed(0)}%)`; if (performance.now() - lastSent > 1200) { lastSent = performance.now(); ws?.sendKeyword(prediction.label, prediction.confidence); } }, onNoGesture: () => { $("prediction").textContent = "No gesture detected"; }, onLowConfidence: () => {}, onLatency: () => {} }); requestAnimationFrame(processFrame); } catch (error) { $("cameraError").textContent = describeCameraError(error); $("cameraError").hidden = false; } }
function processFrame() { if (landmarker && $("video").readyState >= HTMLMediaElement.HAVE_CURRENT_DATA) { const video = $("video"), overlay = $("overlay"); overlay.width = video.videoWidth || 640; overlay.height = video.videoHeight || 480; const result = landmarker.detectForVideo(video, performance.now()); if (isHandLandmarksResult(result)) { const observation = interpretHandLandmarkerResult(result); drawHandOverlay(context, observation.visibleHands, overlay.width, overlay.height); inference?.pushFrame(observation.frameVector); } } requestAnimationFrame(processFrame); }
