"""
Train a Bidirectional LSTM model on ISL landmark data.
Outputs: trained model, confusion matrix, training history, metadata.
"""

import json
import argparse
import numpy as np
from pathlib import Path
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import matplotlib.pyplot as plt

def build_bilstm_model(num_frames: int, num_features: int, num_classes: int) -> tf.keras.Model:
    """
    Build Bidirectional LSTM model for gesture classification.
    
    Architecture:
    - Input: (batch_size, 30 frames, 126 features per frame)
    - BiLSTM 1: 64 units, processes sequence forward and backward
    - Dropout: 30% (regularization)
    - BiLSTM 2: 32 units, further temporal processing
    - Dropout: 30%
    - Dense: 32 units with ReLU (feature aggregation)
    - Dropout: 20%
    - Output: softmax over num_classes (gesture labels)
    
    Total params: ~176K (manageable for TensorFlow.js)
    """
    model = Sequential([
        Bidirectional(
            LSTM(64, return_sequences=True),
            input_shape=(num_frames, num_features)
        ),
        Dropout(0.3),
        Bidirectional(LSTM(32, return_sequences=False)),
        Dropout(0.3),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(num_classes, activation='softmax')
    ])
    
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss='sparse_categorical_crossentropy',  # For integer labels (0, 1, 2, ...)
        metrics=['accuracy']
    )
    
    return model


def load_label_encoder(encoder_path: Path) -> tuple[list[str], dict[str, int], dict[int, str]]:
    """Load and validate the versioned encoder written by build_dataset.py."""
    with encoder_path.open(encoding="utf-8") as handle:
        encoder_payload = json.load(handle)
    required_encoder_fields = {"classes", "label_to_index", "index_to_label"}
    if not required_encoder_fields.issubset(encoder_payload):
        raise ValueError("label_encoder.json must be generated by build_dataset.py and contain classes, label_to_index, and index_to_label.")
    classes = encoder_payload["classes"]
    label_mapping = encoder_payload["label_to_index"]
    idx_to_label = {int(index): label for index, label in encoder_payload["index_to_label"].items()}
    if set(classes) != set(label_mapping) or set(idx_to_label) != set(range(len(classes))):
        raise ValueError("label_encoder.json is internally inconsistent.")
    return classes, label_mapping, idx_to_label

def train_model(data_dir: Path, output_dir: Path):
    """
    Load preprocessed data, build model, train, and evaluate.
    """
    
    # Load splits
    print("=" * 60)
    print("🚀 BiLSTM Training Pipeline")
    print("=" * 60)
    
    print("\n📂 Loading preprocessed data...")
    X_train = np.load(data_dir / "X_train.npy")
    y_train = np.load(data_dir / "y_train.npy")
    X_val = np.load(data_dir / "X_val.npy")
    y_val = np.load(data_dir / "y_val.npy")
    X_test = np.load(data_dir / "X_test.npy")
    y_test = np.load(data_dir / "y_test.npy")
    
    classes, label_mapping, idx_to_label = load_label_encoder(data_dir / "label_encoder.json")
    num_classes = len(classes)

    if num_classes < 2:
        raise ValueError("Training requires at least two classes. Collect all MVP labels before training.")
    num_frames, num_features = X_train.shape[1], X_train.shape[2]
    
    print(f"✅ Data loaded:")
    print(f"   Training:   {X_train.shape} → {y_train.shape}")
    print(f"   Validation: {X_val.shape} → {y_val.shape}")
    print(f"   Test:       {X_test.shape} → {y_test.shape}")
    print(f"   Num classes: {num_classes}")
    print(f"   Label mapping: {label_mapping}")
    
    # Build model
    print("\n🏗️  Building BiLSTM model...")
    model = build_bilstm_model(num_frames, num_features, num_classes)
    
    print("\nModel architecture:")
    model.summary()
    
    # Callbacks
    if (output_dir / "model.h5").exists():
        raise FileExistsError(
            f"Refusing to overwrite existing model artifact: {output_dir / 'model.h5'}. "
            "Choose a new --output-dir for each training run."
        )
    output_dir.mkdir(parents=True, exist_ok=True)
    
    early_stop = EarlyStopping(
        monitor='val_loss',
        patience=15,
        restore_best_weights=True,
        verbose=1
    )
    
    checkpoint = ModelCheckpoint(
        output_dir / "best_model.weights.h5",
        monitor='val_accuracy',
        save_best_only=True,
        save_weights_only=True,
        verbose=0
    )
    
    # Train
    print("\n🚀 Training model...")
    print(f"   Epochs: 100 (early stopping if no improvement for 15 epochs)")
    print(f"   Batch size: 8")
    print(f"   Learning rate: 0.001\n")
    
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=100,
        batch_size=8,
        callbacks=[early_stop, checkpoint],
        verbose=1
    )
    
    # Evaluate on test set
    print("\n" + "=" * 60)
    print("📊 Evaluating on test set...")
    print("=" * 60)
    test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"\n✅ Test Loss: {test_loss:.4f}")
    print(f"✅ Test Accuracy: {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")
    
    # Predictions and confusion matrix
    print("\n🔍 Computing predictions...")
    y_pred_probs = model.predict(X_test, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)
    
    from sklearn.metrics import confusion_matrix, classification_report
    cm = confusion_matrix(y_test, y_pred)
    
    report = classification_report(
        y_test, y_pred,
        labels=list(range(num_classes)),
        target_names=[idx_to_label[i] for i in range(num_classes)],
        zero_division=0,
        digits=4
    )
    
    print("\n📋 Classification Report:")
    print(report)
    
    # Plot confusion matrix
    print("\n📈 Plotting confusion matrix...")
    import seaborn as sns
    
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(
        cm, 
        annot=True, 
        fmt='d', 
        cmap='Blues',
        xticklabels=[idx_to_label[i] for i in range(num_classes)],
        yticklabels=[idx_to_label[i] for i in range(num_classes)],
        ax=ax,
        cbar_kws={'label': 'Count'}
    )
    plt.title('Confusion Matrix - Test Set', fontsize=14, fontweight='bold')
    plt.ylabel('True Label', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig(output_dir / "confusion_matrix.png", dpi=150)
    print(f"✅ Saved: {output_dir / 'confusion_matrix.png'}")
    plt.close()
    
    # Plot training history
    print("📈 Plotting training history...")
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    
    ax1.plot(history.history['loss'], label='Training Loss', linewidth=2)
    ax1.plot(history.history['val_loss'], label='Validation Loss', linewidth=2)
    ax1.set_title('Model Loss', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Loss', fontsize=11)
    ax1.set_xlabel('Epoch', fontsize=11)
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    ax2.plot(history.history['accuracy'], label='Training Accuracy', linewidth=2)
    ax2.plot(history.history['val_accuracy'], label='Validation Accuracy', linewidth=2)
    ax2.axhline(y=test_accuracy, color='r', linestyle='--', label=f'Test Accuracy ({test_accuracy:.2%})', linewidth=2)
    ax2.set_title('Model Accuracy', fontsize=12, fontweight='bold')
    ax2.set_ylabel('Accuracy', fontsize=11)
    ax2.set_xlabel('Epoch', fontsize=11)
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_dir / "training_history.png", dpi=150)
    print(f"✅ Saved: {output_dir / 'training_history.png'}")
    plt.close()
    
    # Save model in both formats
    print("\n💾 Saving model...")
    model.save(output_dir / "model.h5")
    print(f"✅ Keras model: {output_dir / 'model.h5'}")
    
    model.export(output_dir / "model_savedmodel")
    print(f"✅ SavedModel format: {output_dir / 'model_savedmodel'}")
    
    # Save metadata (used by frontend for inference)
    metadata = {
        "model_type": "BiLSTM",
        "num_classes": num_classes,
        "num_frames": num_frames,
        "num_features": num_features,
        "label_mapping": label_mapping,
        "test_accuracy": float(test_accuracy),
        "test_loss": float(test_loss),
        "training_epochs": len(history.history['loss']),
        "confidence_threshold": 0.70,
        "framework": "TensorFlow/Keras",
        "input_shape": [num_frames, num_features],
        "output_classes": sorted([idx_to_label[i] for i in range(num_classes)])
    }
    
    with open(output_dir / "model_metadata.json", 'w') as f:
        json.dump(metadata, f, indent=2)
    print(f"✅ Metadata: {output_dir / 'model_metadata.json'}")
    
    print("\n" + "=" * 60)
    print("✨ Training Complete!")
    print("=" * 60)
    print(f"\n📊 Results Summary:")
    print(f"   Test Accuracy: {test_accuracy*100:.2f}%")
    print(f"   Test Loss: {test_loss:.4f}")
    print(f"   Training Epochs: {len(history.history['loss'])}")
    print(f"\n🎯 Next steps:")
    print(f"   1. Run convert_to_tfjs.py to convert model for browser")
    print(f"   2. Copy model_metadata.json to frontend/model/")
    print(f"   3. Update frontend/js/main.js to load the model")
    
    return model, history, test_accuracy, test_loss

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train a BiLSTM on a versioned ISL dataset.")
    parser.add_argument("--data-dir", default=None, help="Processed dataset version directory.")
    parser.add_argument("--output-dir", default=None, help="Directory for trained model artifacts.")
    args = parser.parse_args()
    script_dir = Path(__file__).parent
    data_dir = Path(args.data_dir) if args.data_dir else script_dir.parent / "dataset" / "processed" / "v1"
    output_dir = Path(args.output_dir) if args.output_dir else script_dir.parent / "saved_model" / f"transit_{data_dir.name}"
    
    if not data_dir.exists():
        print(f"❌ Data directory not found: {data_dir}")
        print("   Run build_dataset.py first!")
        exit(1)
    
    model, history, accuracy, loss = train_model(data_dir, output_dir)
